<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2018 LibreWorks contributors
 * @license   Apache-2.0
 */
namespace Caridea\Validate;

/**
 * Generated by hand.
 */
class ParserTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @covers Caridea\Validate\Parser::__construct
     * @covers Caridea\Validate\Parser::isAssociative
     */
    public function testIsAssociative()
    {
        $object = new Parser(new Registry());
        $this->assertTrue($object->isAssociative(['foo' => 'bar']));
        $this->assertTrue($object->isAssociative([0 => 'aoeu', 'foo' => 'bar']));
        $this->assertFalse($object->isAssociative(['foo', 'bar']));
        $this->assertFalse($object->isAssociative([0 => 'aoeu', 1 => 'bar']));
    }
}
