<?php
namespace Caridea\Validate\Rule;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-03 at 13:33:02.
 */
class TimezoneTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Timezone
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = Timezone::timezone();
    }

    /**
     * @covers Caridea\Validate\Rule\Timezone::apply
     * @covers Caridea\Validate\Rule\Timezone::timezone
     */
    public function testApply()
    {
        $this->assertEquals('FORMAT_ERROR', $this->object->apply([]));
        $this->assertNull($this->object->apply('America/New_York'));
        $this->assertEquals('WRONG_TIMEZONE', $this->object->apply('foobar'));
    }
}
