<?php
declare(strict_types=1);
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2018 LibreWorks contributors
 * @license   Apache-2.0
 */
namespace Caridea\Validate\Rule;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-03 at 13:33:02.
 */
class TimezoneTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Timezone
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = Timezone::timezone();
    }

    /**
     * @covers Caridea\Validate\Rule\Timezone::__construct
     * @covers Caridea\Validate\Rule\Timezone::apply
     * @covers Caridea\Validate\Rule\Timezone::timezone
     */
    public function testApply()
    {
        $this->assertEquals(['FORMAT_ERROR'], $this->object->apply([]));
        $this->assertNull($this->object->apply('America/New_York'));
        $this->assertEquals(['WRONG_TIMEZONE'], $this->object->apply('foobar'));
    }
}
